# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 18:56
from __future__ import unicode_literals
import os
from sys import path
from django.core.management import call_command
from django.core import serializers
from django.db import migrations



def load_fixture(apps, schema_editor):
    call_command('loaddata', 'genres.json', app_label='quickstart') 
    call_command('loaddata', 'artists.json', app_label='quickstart') 
    call_command('loaddata', 'albums.json', app_label='quickstart') 
    call_command('loaddata', 'songs.json', app_label='quickstart') 



class Migration(migrations.Migration):  

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_fixture),
    ]